language: java
jdk:
  - openjdk8
#  - oraclejdk8
#  - oraclejdk9
  
before_install:
  - sh ./build-vlog-library.sh
  - mvn initialize

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2
