language: java
jdk:
  - openjdk8
#  - oraclejdk8
#  - oraclejdk9

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_install:
#  - sudo apt-get install gcc-5 -y
  - sh ./build-vlog-library.sh

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura

dist: trusty
sudo: false

cache:
  directories:
    - ./local_builds
    - $HOME/.m2
